### ISSUE TITLE
Questions about "wun"

### ISSUE THREAD

**Issue by danchoi** [douglascrockford/howjavascriptworks#12]
I'm enjoying the print version of the book. Thank you for writing it. 

I have a few questions about your proposal to use the spelling "wun" instead of "one":

If we change the spelling of "one" to "wun", then we will obscure some non-trivial etymological connections. Have you considered this side effect of your orthographical bugfix?

"Alone" is etymologically related to "one". "lone" is a shortened form of "alone". "Lonely" derives from "lone". Also related is "lonesome" and "loner." If we adopt "wun" as the correct spelling for "one," these related words will be living reminders of the old spelling. What should we do with this inconsistency? Live with it?

The word "none" is also etymologically related to "one". Perhaps we should change "none" to "nun"? But "nun" is already taken.

The word "only" is also etymologically akin to "one". Should we change both the pronunciation and spelling of "only," to "wunly", or perhaps "unly"?

**Comment by douglascrockford** [comment]
Spelling reform is difficult business. Wun word at a time.
