### ISSUE TITLE
deconstruct.js

### ISSUE THREAD

**Issue by cipherlogs** [douglascrockford/howjavascriptworks#14]
Hello Douglas, I'm going through your book and enjoying every step. but I'm struggling now to understand why -1128 as a starting point for the exponent.

and also why do we need to add the exponent of Number.MIN_VALUE

to my understanding we are choosing a negative exponent so that we can add precision later by shifting zeros to the left.

for example (in base 10)
1 * 10**-4 = 0.0001
1 * 10**-2 = 0.01

that means if I try to represent the coefficient of 1 while the exponent is -4 it will be a lot more precise than if I do it with the exponent -2. right?

but the coefficient isn't binary represented so why -53

any hints or links to other resources would help.

Thank you so much for all the work you do

```
// Reduce the coefficient: We can obtain the exponent by dividing the number by
// two until it goes to zero. We add the number of divisions to -1128, which is
// the exponent of 'Number.MIN_VALUE' minus the number of bits in the
// significand minus the bonus bit.

        exponent = -1128;
        let reduction = coefficient;
        while (reduction !== 0) {

// This loop is guaranteed to reach zero. Each division will decrement the
// exponent of the reduction. When the exponent is so small that it can not
// be decremented, then the internal subnormal significand will be shifted
// right instead. Ultimately, all of the bits will be shifted out.

            exponent += 1;
            reduction /= 2;
        }
```

**Comment by douglascrockford** [comment]
These numbers are a consequence of the IEEE 754 standard.
