### ISSUE TITLE
deconstrcut(Number.MIN_VALUE)

### ISSUE THREAD

**Issue by jnydutra** [douglascrockford/howjavascriptworks#4]
When I run the code above i get this result:
{ sign: 1,
  coefficient: 9007199254740992,
  exponent: -1127,
  number: 5e-324 }

But when I try to construct this number using the formula `number = sign * coefficient * ( 2 ** exponent )` I got 0 (Zero).

The small exponent that works with the formula is:

`deconstruct( 1 * 9007199254740992* (2**-1074) );    // => 4.450147717014403e-308`
`deconstruct( 1 * 9007199254740992* (2**-1075) );    // => 0`

I didn't get it. I'm still on chapter 2. So if i find the answer later I will put it here.

Thanks for this amazing book!

**Comment by douglascrockford** [comment]
You need chapter 3.

**Comment by jnydutra** [comment]
I not asking about how to construct numbers bigger or small using bigint ou bigfloat.

My question is about why the formula doesn't work. Maths should work inside de boundaries, right? There's a safe minimal value to work with? (float value, not MIN_SAFE_INTEGER)
