### ISSUE TITLE
How to implement type methods (like str.toUpperCase()) in Neo?

### ISSUE THREAD

**Issue by AlienKevin** [douglascrockford/howjavascriptworks#7]
Dear Mr. Crockford,
Hi, I love your book and Neo as a language prototype. I'm trying to expand Neo into a full-fledged language with static type checking. Neo has most essential features of a language but I can't find a way to add methods to built-in types like text. I'm not familiar with functional programming. However, based on my google search, Clojure implemented type methods using the syntax like `clojure.string/upper-case "MiXeD cAsE"`. So in Neo, should I use something like `text.upper("MiXeD cAsE")` which is a function method that translates to `text("upper", ["MiXeD cAsE"])`? Then in the runtime text() function, I will need to handle the specific case where the first argument is a text and the second is a list of texts.

This approach seems possibly ambiguous to me because maybe in the future I want to implement some feature like 
```
// split a text with subtexts listed
text("Start of a sentence, then end it. Another sentence.", [",", "."])
// output: ["Start of a sentence", " then end it", " Another sentence", ""]
```
which has the same parameter types as `text.upper()`.

What's your recommended implementation of type methods in Neo?

**Comment by douglascrockford** [comment]
I recommend using functions instead of methods. Take a look at Rebol. http://www.rebol.com/

**Comment by AlienKevin** [comment]
Thanks, Rebol is a great inspiration. I think the idea of global functions are cool and the only drawback I can see is the loss of nice instance method chaining syntax like:
```
array.filter(element => element % 2 === 0).map(element => element * 2)
```

**Comment by AlienKevin** [comment]
I think to make function calls more intuitive, current function's method call syntax:
```
foo.bar(arg1, arg2, arg3) = foo("bar", arg1, arg2, arg3)
```
can be changed into instance method calls (assuming arg1 is the instance):
```
arg1.foo(arg2, arg3) = foo(arg1, arg2, arg3)
```
A practical example will be `map` function for arrays:
```
def map: f arr, func {
	result: []
	var i: 0
        loop
                if i < length(arr)
                         break
		let result[]: func(arr[i])
		i: i + 1
	return result
}
```
Without adding the instance method syntax, `map` must be called like this:
```
map([1, 2, 3], f n (n * 2))
```
but now can be written more naturally as
```
[1, 2, 3].map(f n (n * 2))
```
which can be chained smoothly with other iterators
```
[1, 2, 3].map(f n (n * 2)).filter(f n (n > 3))
```
This is also what Python does with its method calls.
