### ISSUE TITLE
How print() works in Neo?

### ISSUE THREAD

**Issue by AlienKevin** [douglascrockford/howjavascriptworks#8]
Dear Mr. Crockford,
How would you implement `print()` in Neo? Consider that we need to use `call print()` to ignore `null` return value and it can get quite verbose. Would you create a new keyword for printing like Python 2?

**Comment by douglascrockford** [comment]
Fortran had a print statement. C did the right thing in getting rid of it.

**Comment by AlienKevin** [comment]
I see. Thanks.
